### PR TITLE
add repository field into package.json to enable `$ npm repo @optimizely/react-sdk`

### PR DESCRIPTION
**Pull request by iamstarkov**

### CODE REVIEW

**Comment by mikechu-optimizely** [comment]
I'm rolling this into #210. Thanks.

**Comment by iamstarkov** [comment]
@mikechu-optimizely seems like #210 never make it to master

**Comment by mikechu-optimizely** [comment]
Thanks for keeping tab @iamstarkov.  You're correct. 

I'm actively updating several points of the associated branch. I made a bit of a mess putting too much into 1 branch (to be overly transparent).  

I'll be cherry-picking into smaller PRs over the next couple of days.

**Comment by mikechu-optimizely** [comment]
I see three PRs
1. Quality of life stuff (including your addition)
2. Updates to the SDK to conform with the JS SDK beta (and future)
3. Bug bash tester app (debating on whether this should be in the repo)

**Comment by mikechu-optimizely** [comment]
Merged this change into main branch. Thanks @iamstarkov  

https://github.com/optimizely/react-sdk/blob/master/package.json#L6

**Pull request closed without merging**
