### PR TITLE
docs: Add example for how to use react hooks to get the context

### PR DESCRIPTION
**Pull request by raphaeleidus**
There are examples for getting the client from the context with the `withOptimizely` HOC but there isn't an example on how to use react hooks to do the same thing.

### CODE REVIEW

**Review by egucciar — APPROVED** [review]

**Comment by mikechu-optimizely** [comment]
Hi @raphaeleidus 

I'm working through the backlog of GitHub Issues and PRs.  Thanks for hanging in there with us.

Please sign the  Contributor License Agreement (CLA) outlined in [CONTRIBUTING](https://github.com/optimizely/react-sdk/blob/master/CONTRIBUTING.md) when you get a second.  

Thanks.

**Comment by mikechu-optimizely** [comment]
@egucciar Thanks for the review 😄

**Comment by raphaeleidus** [comment]
@mikechu-optimizely done

**Comment by mikechu-optimizely** [comment]
I'm rolling this into #210 (which I dislike having become a hodgepodge of commits)  I need to end the madness shortly here.

**Pull request closed without merging**
